import HoldTypeOpenAI

typealias OpenAITranscriptionServing = HoldTypeOpenAI.OpenAITranscriptionServing
typealias OpenAITranscriptionService = HoldTypeOpenAI.OpenAITranscriptionService
typealias OpenAITranscriptionServiceError = HoldTypeOpenAI.OpenAITranscriptionServiceError
typealias OpenAITranscriptionRequestBuilderError =
    HoldTypeOpenAI.OpenAITranscriptionRequestBuilderError

typealias OpenAITextCorrectionServing = HoldTypeOpenAI.OpenAITextCorrectionServing
typealias OpenAITextCorrectionService = HoldTypeOpenAI.OpenAITextCorrectionService
typealias OpenAITextCorrectionServiceError = HoldTypeOpenAI.OpenAITextCorrectionServiceError

typealias OpenAITextTranslationServing = HoldTypeOpenAI.OpenAITextTranslationServing
typealias OpenAITextTranslationService = HoldTypeOpenAI.OpenAITextTranslationService
typealias OpenAITextTranslationServiceError = HoldTypeOpenAI.OpenAITextTranslationServiceError
